pipeline {
  agent any
  tools {
    nodejs '12.10.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stage('Git') {
		git 'https://github.com/StickCruz92/node-test-jenkins.git'
	}

  stages {
    stage('Build') {
      steps {
        echo "Hello World!"
      }
    }
  }
}
